services:
  db:
    image: postgres:15-alpine
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_INTERNAL_PORT}"

  app:
    build: .
    container_name: fastapi_app
    restart: always
    command:
      sh -c "alembic upgrade head && uvicorn app.main:app --host ${SERVER_HOST} --port ${SERVER_PORT} --reload"
    volumes:
      - .:/app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_INTERNAL_HOST}:${DB_INTERNAL_PORT}/${DB_NAME}
    depends_on:
      - db

volumes:
  postgres_data:
