services:
  # База данных PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

 # Бэкенд (FastAPI)
  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: fastapi_app
    restart: always
    command:
      sh -c "alembic upgrade head && uvicorn src.main:app --host ${BACKEND_IP} --port ${BACKEND_PORT} --reload"
    volumes:
      - .:/src
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_INTERNAL_IP}:${DB_INTERNAL_PORT}/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy # Ждет, пока БД станет "здоровой"
    healthcheck:
      # Проверяем доступность API.
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:${BACKEND_PORT}/docs" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s # Даем приложению 10 сек на загрузку библиотек перед первой проверкой


  # Фронтенд (Python SimpleHTTPServer)
  frontend:
    build: frontend
    container_name: frontend_app
    command:
      sh -c "echo 'Starting frontend server...' && python3 -m http.server ${FRONTEND_PORT} --bind 0.0.0.0"
    volumes:
      - .:/frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env
    depends_on:
      api:
        condition: service_healthy # Ждет, пока бэкенд станет "здоровым"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${FRONTEND_PORT}" ]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  postgres_data: