"""add_diet_2

Revision ID: 83ec4e0428ef
Revises: f7d7abe5ac3c
Create Date: 2026-04-27 13:33:26.238386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ec4e0428ef'
down_revision: Union[str, Sequence[str], None] = 'f7d7abe5ac3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diet_food', sa.Column('diet_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('diet_food_user_id_fkey'), 'diet_food', type_='foreignkey')
    op.create_foreign_key(None, 'diet_food', 'diets', ['diet_id'], ['id'])
    op.drop_column('diet_food', 'user_id')
    op.add_column('diets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'diets', ['user_id'])
    op.create_foreign_key(None, 'diets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diets', type_='foreignkey')
    op.drop_constraint(None, 'diets', type_='unique')
    op.drop_column('diets', 'user_id')
    op.add_column('diet_food', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'diet_food', type_='foreignkey')
    op.create_foreign_key(op.f('diet_food_user_id_fkey'), 'diet_food', 'diets', ['user_id'], ['id'])
    op.drop_column('diet_food', 'diet_id')
    # ### end Alembic commands ###
